version: '3'

services:
  pdf2markdown:
    build: .
    container_name: pdf2markdown
    ports:
      - "3000:3000"
    restart: unless-stopped
    environment:
      - PORT=3000
      - DEBUG=False
      - PYTHONUNBUFFERED=1
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 5s
    volumes:
      - pdf2md_logs:/app/logs
    
volumes:
  pdf2md_logs: